---

roles:
  - lkiesow.dnf_autoupdate
  - elan.opencast_activemq
  - elan.opencast_elasticsearch
  - elan.opencast_firewalld
  - elan.opencast_postgresql
  - elan.opencast_repository
  - elan.opencast_selinux
  - elan.opencast_user

collections:
  - community.postgresql
