---

roles:
  - lkiesow.dnf_autoupdate
  - elan.opencast_elasticsearch
  - elan.opencast_firewalld
  - elan.opencast_postgresql
  - name: elan.opencast_repository
    version: "1.0.0"
  - elan.opencast_selinux
  - name: elan.opencast_user
    version: "1.0.0"

collections:
  - community.postgresql
